### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by MyNewBie** [jossalgon/teamSpeakTelegram#5]
https://pastebin.com/jdMi5Krt
whats the problem ? I install python-telegram-bot but it say python-telegram-bot wasn't properly installed.

i did install this packages :
system : debian
python3
certifi-2017.7.27.1
future-0.16.0
blinker-1.4
PyMySQL-0.7.11
ts3-1.0.6
python-telegram-bot 7.0.1

**Comment by jossalgon** [comment]
TeamSpeakTelegram installs all the dependencies it needs, try:
```
pip3 uninstall teamSpeakTelegram
pip3 install teamSpeakTelegram
python3 -m teamSpeakTelegram
```

**Comment by MyNewBie** [comment]
ok I did it manually , everything work ok. thanks

**Comment by jossalgon** [comment]
Great, enjoy it! I'll close this issue. 
Of course, I am available for any questions or suggestions.
